ecomdataops:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ax09080.eu-west-3.aws
      user: AnassEnasmien
      password: riLBi6XPNuShq8c
      warehouse: ECOMMERCE_WAREHOUSE
      database: ECOMMERCE_DB
      schema: RAW
      threads: 1
